# Generated by Django 5.1.3 on 2024-11-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/female-default-profile.webp', null=True, upload_to='profile_pics/'),
        ),
    ]
