# Generated by Django 5.1.3 on 2024-11-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/female-default-profile.webp', null=True, upload_to='profile_pics/'),
        ),
    ]
