# Generated by Django 5.1.3 on 2024-11-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField(max_length=200)),
                ('movie_in_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_in_room', to='movies.movie')),
                ('users_in_room', models.ManyToManyField(blank=True, related_name='users_in_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
